/*****************************************************************************
* Model: calc_stm32f469i-disco.qm
* File:  ./calc.h
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${.::calc.h} .............................................................*/
#ifndef calc_h
#define calc_h

#include "main.h"

enum CalcSignals {
    C_SIG = Q_USER_SIG,
    CE_SIG,
    DIGIT_0_SIG,
    DIGIT_1_9_SIG,
    POINT_SIG,
    OPER_SIG,
    EQUALS_SIG,
    OFF_SIG,    /* not used */
    TOUCH_SIG,    /* new */
    MAX_SIG
};

/*${Events::CalcEvt} .......................................................*/
typedef struct {
/* protected: */
    QEvt super;

/* public: */
    uint8_t key_code;
} CalcEvt;

/*${Events::TouchscreenEvt} ................................................*/
typedef struct {
/* protected: */
    QEvt super;
} TouchscreenEvt;

/*${AOs::Calc_ctor} ........................................................*/
void Calc_ctor(void);

extern QActive *const AO_Calc;

/*${AOs::Touchscreen_ctor} .................................................*/
void Touchscreen_ctor(void);

extern QActive *const AO_Touchscreen;


#endif /* calc_h */
