/*****************************************************************************
* Model: qhsmtst_stm32f469i-disco.qm
* File:  ./qhsmtst.h
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${.::qhsmtst.h} ..........................................................*/
#ifndef qhsmtst_h
#define qhsmtst_h

#include "main.h"

enum QHsmTstSignals {
    A_SIG = Q_USER_SIG,
    B_SIG,
    C_SIG,
    D_SIG,
    E_SIG,
    F_SIG,
    G_SIG,
    H_SIG,
    I_SIG,
    TOUCH_SIG, /* new */
    TERMINATE_SIG, /* unused */
    IGNORE_SIG, /* unused */
    MAX_SIG
};

/*${Events::QHsmTstEvt} ....................................................*/
typedef struct {
/* protected: */
    QEvt super;
} QHsmTstEvt;

/*${Events::TouchscreenEvt} ................................................*/
typedef struct {
/* protected: */
    QEvt super;
} TouchscreenEvt;

/*${AOs::QHsmTst_ctor} .....................................................*/
void QHsmTst_ctor(void);

extern QActive *const AO_QHsmTst;

/*${AOs::Touchscreen_ctor} .................................................*/
void Touchscreen_ctor(void);

extern QActive *const AO_Touchscreen;


#endif /* qhsmtst_h */
